name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm test
        env:
          CI: true
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
